//SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.9;

contract SVG1 {

    function getSvgPart1(string memory color) external pure returns(string memory) {
        return string(
            abi.encodePacked(
                '<defs>', 
                    '<style>', 
                        "@import url('https://fonts.googleapis.com/css2?family=Abril+Fatface');", 
                        "@import url('https://fonts.googleapis.com/css2?family=Codystar:wght@300');", 
                        "@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700;800');", 
                        "@import url('https://fonts.googleapis.com/css2?family=Meie+Script');", 
                        "@import url('https://fonts.googleapis.com/css2?family=Mrs+Saint+Delafield');", 
                        "@import url('https://fonts.googleapis.com/css2?family=Rubik+Distressed');", 
                        '.cls-1, .cls-2, .cls-3, .cls-4, .cls-5, .cls-6, .cls-7, .cls-8, .cls-9, .cls-10, .cls-11, .cls-12, .cls-13, .cls-14, .cls-15, .cls-16, .cls-17 { fill: none; }', 
                        '.cls-18, .cls-3, .cls-4, .cls-5, .cls-6, .cls-7, .cls-8, .cls-9, .cls-10, .cls-11, .cls-19, .cls-12, .cls-13, .cls-14, .cls-15, .cls-16, .cls-17 {stroke: ', color, '; }', 
                        '.cls-29, .cls-30 { fill: ', color, '; }', 
                        '.cls-18, .cls-3, .cls-5, .cls-7, .cls-8, .cls-11, .cls-19, .cls-12, .cls-13, .cls-14, .cls-15 { stroke-miterlimit: 10; }', 
                        '.cls-18, .cls-6, .cls-8 { stroke-width: 2.5px; }', 
                        '.cls-18, .cls-20, .cls-21, .cls-19 { fill: #fff; }', 
                        '.cls-2, .cls-4, .cls-6, .cls-21, .cls-9, .cls-10, .cls-16, .cls-17 { stroke-linecap: round; stroke-linejoin: round; }', 
                        '.cls-2, .cls-21 { stroke: #fff; }', 
                        '.cls-3, .cls-16 { stroke-width: 1.5px; }', 
                        '.cls-4 { stroke-width: 1.4px;}', 
                        '.cls-5, .cls-17 {stroke-width: 3px;}', 
                        '.cls-22 {fill: #ef6048;', 
                        "font-family: RubikDistressed-Regular, 'Rubik Distressed';", 
                        '}', 
                        '.cls-22, .cls-23, .cls-24 { font-size: 24px; }', 
                        '.cls-25 { clip-path: url(#clippath); }', 
                        '.cls-26 { letter-spacing: -.08em; }', 
                        '.cls-27 { letter-spacing: -.01em; }', 
                        '.cls-28 { letter-spacing: 0em; }', 
                        '.cls-31 { fill: #8e8e8e; }', 
                        '.cls-32, .cls-33 {fill: #47d80b;}', 
                        '.cls-7 { stroke-width: 2.3px; }', 
                        '.cls-21, .cls-10, .cls-12 {stroke-width: 2px;}', 
                        '.cls-30 {', 
                        'font-family: Futura-Medium, Futura;', 
                        'font-size: 13px;', 
                        '}', 
                        '.cls-34 {', 
                        'letter-spacing: .02em;', 
                        '}', 
                        '.cls-35 {', 
                        'letter-spacing: -.1em;', 
                        '}', 
                        '.cls-9 {', 
                        'stroke-width: 25px;', 
                        '}', 
                        '.cls-36 {', 
                        'fill: #48d8ff;', 
                        "font-family: MeieScript-Regular, 'Meie Script';", 
                        'font-size: 72.68px;', 
                        'letter-spacing: -.04em;', 
                        '}', 
                        '.cls-37 {', 
                        'letter-spacing: -.03em;', 
                        '}', 
                        '.cls-38 {', 
                        'clip-path: url(#clippath-1);', 
                        '}', 
                        '.cls-39 {', 
                        'clip-path: url(#clippath-3);', 
                        '}', 
                        '.cls-40 {', 
                        'clip-path: url(#clippath-2);', 
                        '}', 
                        '.cls-41 {', 
                        'letter-spacing: 0em;', 
                        '}', 
                        '.cls-42 {', 
                        'letter-spacing: 0em;', 
                        '}', 
                        '.cls-43 {', 
                        'font-family: Inter-Regular, Inter;', 
                        'font-size: 38px;', 
                        '}', 
                        '.cls-44 {', 
                        'letter-spacing: -.05em;', 
                        '}', 
                        '.cls-11 {', 
                        'stroke-width: 2.6px;', 
                        '}', 
                        '.cls-45 {', 
                        'font-family: Inter-Bold, Inter;', 
                        'font-size: 40px;', 
                        '}', 
                        '.cls-46 {', 
                        'letter-spacing: 0em;', 
                        '}', 
                        '.cls-13 {', 
                        'stroke-width: 1.6px;', 
                        '}', 
                        '.cls-47 {', 
                        'fill: #707070;', 
                        'font-family: Codystar-Light, Codystar;', 
                        'font-size: 96px;', 
                        '}', 
                        '.cls-23 {', 
                        'fill: #444;', 
                        '}', 
                        '.cls-23, .cls-24 {', 
                        'font-family: Inter-Medium, Inter;', 
                        '}', 
                        '.cls-48 {', 
                        'fill: #002649;', 
                        'font-family: Inter;', 
                        'font-weight: 800;', 
                        'font-size: 114px;', 
                        '}', 
                        '.cls-14 {', 
                        'stroke-width: 1.8px;', 
                        '}', 
                        '.cls-49 {', 
                        'letter-spacing: 0em;', 
                        '}', 
                        '.cls-50 {', 
                        'letter-spacing: -.05em;', 
                        '}', 
                        '.cls-51 {', 
                        'letter-spacing: 0em;}', 
                        '.cls-15 {stroke-width: 2.2px;}', 
                        '.cls-52 {', 
                        "font-family: MrsSaintDelafield-Regular, 'Mrs Saint Delafield';", 
                        'font-size: 172px; text-align:right; text-anchor:end;', 
                        '}', 
                        '.cls-53 {letter-spacing: -.03em;}', 
                        '.cls-54 {letter-spacing: -.02em;}', 
                        '.cls-55 {letter-spacing: 0em;}', 
                        '.cls-56 {letter-spacing: -.03em;}', 
                        '.cls-57, .cls-33 {font-size: 110px;}', 
                        '.cls-57, .cls-33, .cls-58 {', 
                        "font-family: AbrilFatface-Regular, 'Abril Fatface';", 
                        '}', 
                        '.cls-57, .cls-58 {fill: #111;}', 
                        '.cls-58 {font-size: 104px;}', 
                    '</style>'
            )
        );
    }

}